# Generated by Django 4.2.4 on 2024-07-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expresion',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='humExt',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='humInt',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='luz',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='luzUV',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modo',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='riego',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='solhoras',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tempExt',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
